version: '0.2'
phases:
  install:
    runtime-versions:
      php: '8.2'
    commands:
    - composer install
  build:
    commands:
    - composer run phpunit
    - composer run phpcs
artifacts:
  type: zip
  files:
    - '**/*'