version: '0.2'
phases:
  install:
    runtime-versions:
      php: '8.2'
    commands:
    - composer install
  build:
    commands:
    - composer run phpunit
    - composer run phpcs
  post_build:
    commands:
    - zip -r slim-build.zip .
    - aws s3 cp slim-build.zip s3://slim-codebuild-bucket
# artifacts:
#   type: zip
#   files:
#     - '**/*'