name: PHP_CodeSniffer
on:
  pull_request:
  push:

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
      - name: Install dependencies
        run: composer install --no-progress --no-suggest
      - name: Run CodeSniffer
        run: composer phpcs
  phpunit:
    needs: phpcs
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install --no-progress --no-suggest
      - name: Run PHPUnit
        run: composer phpunit