name: PHP_CodeSniffer
on:
  pull_request:
    paths:
      - 'src/**'
  push:
    paths:
      - 'src/**'

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        users: shivammathur/setup-php@v2
      - name: Install dependencies
        run: composer install --no-progress --no-suggest
      - name: Run CodeSniffer
        run: composer run phpcs