name: PHP_CodeSniffer
on:
  pull_request:
    # paths:
    #   - 'src/**'
  push:
    # paths:
    #   - 'src/**'

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
      - name: Install dependencies
        run: composer install --no-progress --no-suggest
      - name: Run PHPUnit
        run: composer run phpunit
  phpcs:
    needs: phpunit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
      - name: Install dependencies
        run: composer install --no-progress --no-suggest
      - name: Run CodeSniffer
        run: composer run phpcs